version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "5001:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080

  frontend:
    build: 
      context: ./client
      args:
        - VITE_API_URL=https://brandburst-api.azurewebsites.net # Your live backend URL
    ports:
      - "80:80"
    depends_on:
      - backend